### ISSUE TITLE
RCL2 MVP TODO

### ISSUE THREAD

**Issue by downthecrop** [downthecrop/RCL2#1]
## Essential

- [x] Supabase Auth Login
- [x] Vuex or Pinia global state
- [x] Public facing profiles
- [x] Ability to delete a link
- [x] Ability to set link visibility (Server Response)

Past here it it works.. I'll start using it. I don't really want to market this so I'm just using a MathX Subdomain (path right now..)

### High Priority 

- [x] Mobile Friendly
- [x] Mobile Friendly "Public" pages
- [x] Basic "Startup" Landingpage

**Comment by downthecrop** [comment]
Also restyle tables to this: https://preline.co/examples/application-tables.html

**Comment by downthecrop** [comment]
LAUNCH

- [ ] Landing page finished
- [ ] Product hunt listing
- [ ] routing fixes for dashboard and supa base redirect
